language: ruby
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:seed
  - bundle exec rspec spec/
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - export DISPLAY=:99.0
rvm:
  - "2.0.0"